[project]
name = "sentisign-stt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mediapipe>=0.10.31",
    "opencv-python>=4.12.0.88",
    "tensorflow>=2.20.0",
]
